#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# This scripts adds local version information from the version
# control systems git, mercurial (hg) and subversion (svn).
#
# If something goes wrong, send a mail the kernel build mailinglist
# (see MAINTAINERS) and CC Nico Schottelius
# <nico-linuxsetlocalversion -at- schottelius.org>.
#
#

usage() {
	echo "Usage: $0 [--save-scmversion] [srctree] [branch] [kmi-generation]" >&2
	exit 1
}

#res="-android14-11-g2c0cf7b3a827-ab14641137"
res="-android14-11-gc1de4747ac59-ab14219743"
scm_only=false
srctree=.
android_release=
kmi_generation=
if test "$1" = "--save-scmversion"; then
	cd "${srctree}"
	echo "g2c0cf7b3a827" > .scmversion
	shift
fi

if test $# -gt 0; then
	srctree=$1
	shift
fi

scm_version()
{
	local short
	short=false

	cd "$srctree"
	echo "g2c0cf7b3a827" > .scmversion

	if test -e .scmversion; then
		cat .scmversion
		return
	fi
	if test "$1" = "--short"; then
		short=true
	fi
}

if $scm_only; then
	if test ! -e .scmversion; then
#		res=$(scm_version)
		echo "g2c0cf7b3a827" > .scmversion
#		echo "$res" >.scmversion
	fi
	exit
fi

if ! test -e include/config/auto.conf; then
	echo "Error: kernelrelease not valid - run 'make prepare' to update it" >&2
	exit 1
fi

# localversion* files in the build and source directory
#res="$(collect_files localversion*)"
#if test ! "$srctree" -ef .; then
#	res="$res$(collect_files "$srctree"/localversion*)"
#fi

# CONFIG_LOCALVERSION and LOCALVERSION (if set)


# scm version string if not at a tagged commit
#fi

echo "$res"
